---
title: "trial"
format: html
editor: visual
---
```{r}
library(tidyverse)
install.packages("effects")
```

```{r}
data <- read.csv("Data /soilresp_midterm.csv")
data
summary(data)
```
```{r}
data_w <- data[-26,] %>% 
  clean_names() %>% 
  
  mutate(
    rep = case_when
    (plot == c(1:5) ~ "1",
    plot == c(6:10) ~ "2",
      plot == c(11:15) ~ "3",
      plot == c(16:20) ~ "4", 
      plot == c(21:25) ~ "5"
     )
  ) %>% 
  pivot_longer(cols =r1_01_29_24:r6_02_07_24,
               values_to = "respiration",
               names_to = "x1")   %>%
  mutate(x1 = gsub("resp", "", x1)) %>% 
   pivot_longer(cols = starts_with("sw"),
               values_to = "watercontent", 
               names_to = "x2"
               ) %>% 
  mutate(x2 = gsub("water", "", x2)) %>% 
  pivot_longer(cols = st1:st6,
               values_to = "soiltemp",
               names_to = "x3") %>% 
  mutate(x3 = gsub("temp", "", x3)) %>% 
 mutate(date1 = str_extract(x1, "\\d{2}_\\d{2}_\\d{2}")
  ) %>% 
  mutate(date = as.Date(date1, "%m_%d_%y")) %>% 
  mutate(dar = case_when(
    date = 2024-01-29 ~ 1,
    date = 2024-01-30 ~ 2, 
    date = 2024-01-31 ~ 3, 
  )) %>% 
  select(c(-x1,-x2,-x3,-date1)) 

data_w
```


Ancova assumptions - 
1. Linearity between the covariate and the response variable
```{r} 
data_w %>% 
  ggscatter(x= "watercontent", y ="respiration",
            color = "treatment", add = "reg.line")+
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..rr.label.., sep = "~~~~"), color = treatment)
    )
```



```{r}
ancova <- lm(respiration ~ watercontent*treatment,
             data = data_w)
anova(ancova)
library(effects)
adj <- effect("treatment", ancova)
plot(adj)
```
```{r}
  mutate(x1 = gsub("resp", "", x1)) %>% 
   pivot_longer(cols = starts_with("sw"),
               values_to = "watercontent", 
               names_to = "x2"
               ) %>% 
  mutate(x2 = gsub("water", "", x2)) %>% 
  pivot_longer(cols = st1:st6,
               values_to = "soiltemp",
               names_to = "x3") %>% 
  mutate(x3 = gsub("temp", "", x3))
```


